name: CD Workflow

on:
    workflow_run:
        workflows: ["CI Workflow"] # Trigger this workflow after the CI Workflow is completed
        types: [completed]

jobs:
    deploy: # job name
        runs-on: ubuntu-latest # Github Runner
        steps:
            - name: Checkout code
              uses: actions/checkout@v4 # clone the code into ubuntu runner
            - name: Execute remote SSH commands using password
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                timeout: 60s # Set a timeout for the SSH connection
                command_timeout: 30m # Set a timeout for the remote command execution
                script: |
                    git clone https://github.com/MeetPatel3366/SkillPulse.git

                    echo "Connected"

                    cd ~/SkillPulse

                    echo "Git pull..."
                    git pull origin main

                    echo "Docker compose pull..."
                    docker compose pull

                    echo "Docker compose down & up..."
                    docker compose down && docker compose up -d

                    echo "Done"
