name: CI Workflow

on:
  push:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true" # Force JavaScript actions to use Node.js 24

jobs:
  build: # job name
    runs-on: ubuntu-latest # Github Runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # clone the code into ubuntu runner

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4 # setup docker buildx
